[project]
name = "openmario-rec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "np>=1.0.2",
    "pandas>=2.2.3",
    "pydantic>=2.11.5",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
]
